/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ListaTarefas;
import BackEnd.Projeto;
import BackEnd.Sistema;
import javax.swing.JOptionPane;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class EditarListaTarefas extends javax.swing.JFrame {

    private Sistema sistemaEditarListaTarefas;
    private Projeto projetoEditarListaTarefas;
    private ListaTarefas listaTarefasEditarListaTarefas;

    public EditarListaTarefas(Sistema sistema, Projeto projeto, ListaTarefas listaTarefas) {
        sistemaEditarListaTarefas = sistema;
        projetoEditarListaTarefas = projeto;
        listaTarefasEditarListaTarefas = listaTarefas;
        initComponents();
        nomeEmptyLabel.setVisible(false); //Começa a janela com o emptyLabel
        setValues(); //Carrega os valores da tarefa
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); //operação de fechar não faz nada
        setTitle(sistemaEditarListaTarefas.NOMEPROGRAMA + " - Editar Lista Tarefas - " + listaTarefasEditarListaTarefas.getNomeListaTarefas()); //Nome da janela
        setIconImage(sistemaEditarListaTarefas.getIconFrame()); //Icon da janela
        setLocationRelativeTo(null); //Janelo no meio do ecrâ
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoProjetoLabel = new javax.swing.JLabel();
        descriçãoLabel = new javax.swing.JLabel();
        títuloLabel = new javax.swing.JLabel();
        títuloTextField = new javax.swing.JTextField();
        criarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        nomeEmptyLabel = new javax.swing.JLabel();
        descriçãoScrollPane = new javax.swing.JScrollPane();
        descriçãoEditorPane = new javax.swing.JEditorPane();
        projetoValue = new javax.swing.JLabel();
        projetoLabel = new javax.swing.JLabel();
        eliminarButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(520, 530));
        setMinimumSize(new java.awt.Dimension(520, 530));
        setResizable(false);

        novoProjetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        novoProjetoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novoProjetoLabel.setText("Editar Lista Tarefas");

        descriçãoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        descriçãoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriçãoLabel.setText("Descrição");

        títuloLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        títuloLabel.setText("Título");

        títuloTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                títuloTextFieldKeyReleased(evt);
            }
        });

        criarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        criarButton.setText("Editar");
        criarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        nomeEmptyLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        nomeEmptyLabel.setForeground(new java.awt.Color(250, 0, 0));
        nomeEmptyLabel.setText("*");

        descriçãoScrollPane.setViewportView(descriçãoEditorPane);

        projetoValue.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetoValueMouseClicked(evt);
            }
        });

        projetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoLabel.setText("Projeto");

        eliminarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        eliminarButton.setText("Eliminar");
        eliminarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eliminarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(descriçãoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(novoProjetoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(títuloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(projetoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(títuloTextField)
                                    .addComponent(projetoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEmptyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addComponent(voltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(eliminarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(criarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(novoProjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(títuloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(títuloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeEmptyLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projetoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(criarButton)
                    .addComponent(eliminarButton))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void títuloTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_títuloTextFieldKeyReleased
        nomeEmptyLabel.setVisible(false); // torna nomeEmptyLabel não visível
        if (títuloTextField.getText().isEmpty()) { // torna nomeEmptyLabel não visível se estiver vazia
            nomeEmptyLabel.setVisible(true);
        }
    }//GEN-LAST:event_títuloTextFieldKeyReleased

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose(); //Faz dispose da janela
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void projetoValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetoValueMouseClicked
        new ProjetoFrontEnd(sistemaEditarListaTarefas, projetoEditarListaTarefas).setVisible(true); //Cria uma instância e torna-la
    }//GEN-LAST:event_projetoValueMouseClicked

    private void criarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarButtonActionPerformed
        if (!sistemaEditarListaTarefas.getCurrentSave().getListaProjetosSave().getListaProjetos().contains(projetoEditarListaTarefas)) { //Se o projeto não for encontrado manda uma mensagem de erro e faz dispose da janela
            JOptionPane.showMessageDialog(this, "Este projeto não existe ou foi eliminado", "Erro ao editar lista tarefas.", JOptionPane.ERROR_MESSAGE);
            dispose();
        }
        if (!projetoEditarListaTarefas.getListasTarefas().contains(listaTarefasEditarListaTarefas)) { //Se a lista não for encontrada manda uma mensagem de erro e faz dispose da janela
            JOptionPane.showMessageDialog(this, "Esta lista não existe ou foi eliminado", "Erro ao editar lista tarefas.", JOptionPane.ERROR_MESSAGE);
            dispose();
        }

        String erro = "";
        if (títuloTextField.getText().isEmpty()) { //Se o título editador for vazio acrescenta 
            erro += "Nome inválido.\n";
            títuloLabel.setVisible(true); //torna o títuloLabel visível 
        }

        if (!erro.isEmpty()) { //Se o erro não for vazio manda uma mensagem de erro com o erro
            JOptionPane.showMessageDialog(this, erro, "Erro ao editar a lista de tarefas", JOptionPane.ERROR_MESSAGE);
        } else { //Se o erro for vazio manda uma mensagem de erro com o erro
            int intConfirmar = JOptionPane.showConfirmDialog(this, "Tem a certeza que pretende editar lista de tarefas " + listaTarefasEditarListaTarefas.getNomeListaTarefas() + " ?", "Confirmação", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);//Mensamgem de confirmação
            if (intConfirmar == 0) {//Se responder SIM
                listaTarefasEditarListaTarefas.setNomeListaTarefas(títuloTextField.getText());//Edita o título da lista 
                listaTarefasEditarListaTarefas.setDescriçãoListaTarefas(descriçãoEditorPane.getText());//Edita a descrição da lista
                sistemaEditarListaTarefas.setSaved(false); //Torna o estado do objeto sistema como não gravado
                sistemaEditarListaTarefas.getDashboardWindow().refreshUI();//Atualiza o estado de todas as janelas de programas.
                dispose();
            }
        }

    }//GEN-LAST:event_criarButtonActionPerformed

    private void eliminarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eliminarButtonActionPerformed

        int intConfirmar = JOptionPane.showConfirmDialog(this, "Tem a certeza que pretende apagar a lista de tarefas " + listaTarefasEditarListaTarefas.getNomeListaTarefas() + " ?", "Confirmação", JOptionPane.OK_CANCEL_OPTION, JOptionPane.WARNING_MESSAGE);//Mensagem de confirmação
        if (intConfirmar == 0) { //Se responder SIM
            if (!sistemaEditarListaTarefas.getCurrentSave().getListaProjetosSave().getListaProjetos().contains(projetoEditarListaTarefas)) { //Se o projeto não for encontrada manda um mensagem de erro e faz dipose da janela
                JOptionPane.showMessageDialog(this, "Este projeto não existe ou foi eliminado", "Erro ao editar lista tarefas.", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
            if (!projetoEditarListaTarefas.getListasTarefas().contains(listaTarefasEditarListaTarefas)) { //Se a lista não for encontrada manda um mensagem de erro
                JOptionPane.showMessageDialog(this, "Esta lista não existe ou foi eliminado", "Erro ao editar lista tarefas.", JOptionPane.ERROR_MESSAGE);
                dispose();
            }
            projetoEditarListaTarefas.getListasTarefas().remove(listaTarefasEditarListaTarefas); //Se a lista não for encontrada manda um mensagem de erro
            sistemaEditarListaTarefas.getDashboardWindow().refreshUI();//Atualiza o estado de todas as janelas de programas.
            dispose();
        }
    }//GEN-LAST:event_eliminarButtonActionPerformed

    public void setValues() {
        projetoValue.setText(projetoEditarListaTarefas.getTítuloProjeto());//Carrega o título do projeto para o label
        títuloTextField.setText(listaTarefasEditarListaTarefas.getNomeListaTarefas()); //Carrega o título da tarefa para o label
        descriçãoEditorPane.setText(listaTarefasEditarListaTarefas.getDescriçãoListaTarefas()); //Carrega a descrição da tarefa
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarButton;
    private javax.swing.JEditorPane descriçãoEditorPane;
    private javax.swing.JLabel descriçãoLabel;
    private javax.swing.JScrollPane descriçãoScrollPane;
    private javax.swing.JButton eliminarButton;
    private javax.swing.JLabel nomeEmptyLabel;
    private javax.swing.JLabel novoProjetoLabel;
    private javax.swing.JLabel projetoLabel;
    private javax.swing.JLabel projetoValue;
    private javax.swing.JLabel títuloLabel;
    private javax.swing.JTextField títuloTextField;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
