/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ListaTarefas;
import BackEnd.Projeto;
import BackEnd.Sistema;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class ListaTarefasFrontEnd extends javax.swing.JFrame {

    private Sistema sistemaNovaListaTarefasFrontEnd;
    private Projeto projetoListaTarefasFrontEnd;
    private ListaTarefas listaTarefasListaTarefasFrontEnd;

    public ListaTarefasFrontEnd(Sistema sistema, Projeto projeto, ListaTarefas listaTarefas) {
        sistemaNovaListaTarefasFrontEnd = sistema;
        projetoListaTarefasFrontEnd = projeto;
        listaTarefasListaTarefasFrontEnd = listaTarefas;
        initComponents();
        setValues(); //Carrega valores da lista
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//Fechar a janela, faz dispose da janela
        setTitle(sistemaNovaListaTarefasFrontEnd.NOMEPROGRAMA + " - Lista Tarefas  - " + listaTarefasListaTarefasFrontEnd.getNomeListaTarefas()); //Título da janela
        setIconImage(sistemaNovaListaTarefasFrontEnd.getIconFrame()); //Ícon da janela
        setLocationRelativeTo(null); //janela no meio do ecrã
        if (listaTarefasListaTarefasFrontEnd.getOwnerListaTarefas() != sistemaNovaListaTarefasFrontEnd.getCurrentUser() && projetoListaTarefasFrontEnd.getOwnerProjeto() != sistemaNovaListaTarefasFrontEnd.getCurrentUser()) {//Se o utilizador atual não for owner da tarefa ou owner do projeto, torna o butão de editar não visivel.
            editarButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoProjetoLabel = new javax.swing.JLabel();
        descriçãoLabel = new javax.swing.JLabel();
        títuloLabel = new javax.swing.JLabel();
        editarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        descriçãoScrollPane = new javax.swing.JScrollPane();
        descriçãoEditorPane = new javax.swing.JEditorPane();
        projetoValue = new javax.swing.JLabel();
        projetoLabel = new javax.swing.JLabel();
        títuloValue = new javax.swing.JLabel();
        ownerLabel = new javax.swing.JLabel();
        ownerValue = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(520, 600));
        setResizable(false);

        novoProjetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        novoProjetoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novoProjetoLabel.setText("Lista Tarefas");

        descriçãoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        descriçãoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriçãoLabel.setText("Descrição");

        títuloLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        títuloLabel.setText("Título");

        editarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        descriçãoEditorPane.setEditable(false);
        descriçãoScrollPane.setViewportView(descriçãoEditorPane);

        projetoValue.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetoValueMouseClicked(evt);
            }
        });

        projetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoLabel.setText("Projeto");

        títuloValue.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N

        ownerLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ownerLabel.setText("Owner");

        ownerValue.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        ownerValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ownerValueMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(novoProjetoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 449, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(títuloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(projetoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ownerLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(projetoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(títuloValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(ownerValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addComponent(descriçãoScrollPane)
                            .addComponent(descriçãoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addComponent(voltarButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(novoProjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(títuloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(títuloValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(projetoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ownerLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ownerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(editarButton))
                .addGap(47, 47, 47))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose(); //dispose da janela
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void projetoValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetoValueMouseClicked
        new ProjetoFrontEnd(sistemaNovaListaTarefasFrontEnd, projetoListaTarefasFrontEnd).setVisible(true); //Abre uma janela do projeto clicado
    }//GEN-LAST:event_projetoValueMouseClicked

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        new EditarListaTarefas(sistemaNovaListaTarefasFrontEnd, projetoListaTarefasFrontEnd, listaTarefasListaTarefasFrontEnd).setVisible(true); //abre uma janela para editar o projeto
        dispose();//dispose da janela
    }//GEN-LAST:event_editarButtonActionPerformed

    private void ownerValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerValueMouseClicked
        new Perfil(sistemaNovaListaTarefasFrontEnd, listaTarefasListaTarefasFrontEnd.getOwnerListaTarefas()).setVisible(true); //abre uma janela do perfil do owner
    }//GEN-LAST:event_ownerValueMouseClicked

    public void setValues() { //Carrega os valores da lista
        projetoValue.setText(projetoListaTarefasFrontEnd.getTítuloProjeto());
        títuloValue.setText(listaTarefasListaTarefasFrontEnd.getNomeListaTarefas());
        descriçãoEditorPane.setText(listaTarefasListaTarefasFrontEnd.getDescriçãoListaTarefas());
        ownerValue.setText(listaTarefasListaTarefasFrontEnd.getOwnerListaTarefas().getNomeUser() + " ( " + listaTarefasListaTarefasFrontEnd.getOwnerListaTarefas().getUsernameUser() + " )");

    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JEditorPane descriçãoEditorPane;
    private javax.swing.JLabel descriçãoLabel;
    private javax.swing.JScrollPane descriçãoScrollPane;
    private javax.swing.JButton editarButton;
    private javax.swing.JLabel novoProjetoLabel;
    private javax.swing.JLabel ownerLabel;
    private javax.swing.JLabel ownerValue;
    private javax.swing.JLabel projetoLabel;
    private javax.swing.JLabel projetoValue;
    private javax.swing.JLabel títuloLabel;
    private javax.swing.JLabel títuloValue;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
