/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ListaTarefas;
import BackEnd.Projeto;
import BackEnd.Sistema;
import BackEnd.Tarefa;
import BackEnd.User;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.DefaultComboBoxModel;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class NovaTarefa extends javax.swing.JFrame {

    private Sistema sistemaNovaTarefa;
    private Projeto projetoNovaTarefa;
    private DefaultListModel usersAssociadosListModel;
    private DefaultComboBoxModel listaTarefasComboModel;

    public NovaTarefa(Sistema sistema, Projeto projeto) {
        sistemaNovaTarefa = sistema;
        projetoNovaTarefa = projeto;
        usersAssociadosListModel = new DefaultListModel();
        listaTarefasComboModel = new DefaultComboBoxModel<ListaTarefas>();
        initComponents();
        setLabelsVisible(false); //torna os labels de erro não visíveis
        setSelectedDate();//carrega a data limite default
        projetoValue.setText(projetoNovaTarefa.getTítuloProjeto()); //Carrega o título do projeto
        setUserListsModels();//Carrega a lista modelo de utilizadores associados do projeto
        setListaTarefasComboModel(); //Carrega a combo box modelo de listas de tarefas do projeto
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//Fechar a janela faz dispose da janela
        setTitle(sistemaNovaTarefa.NOMEPROGRAMA + " - Nova Tarefa");//Título da janel
        setIconImage(sistemaNovaTarefa.getIconFrame()); //Ícon da janela    
        setLocationRelativeTo(null); //Janela centrada no ecrã

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoProjetoLabel = new javax.swing.JLabel();
        descriçãoLabel = new javax.swing.JLabel();
        títuloLabel = new javax.swing.JLabel();
        títuloTextField = new javax.swing.JTextField();
        selecionarButton = new javax.swing.JButton();
        dataLimiteLabel = new javax.swing.JLabel();
        userAssociadosTabbedPane = new javax.swing.JTabbedPane();
        userAssociadosScrollPane = new javax.swing.JScrollPane();
        userAssociadosLista = new javax.swing.JList<>();
        criarButton = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        horasLimiteComboBox = new javax.swing.JComboBox<>();
        minutosLimiteComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataLimiteChooserCombo = new datechooser.beans.DateChooserCombo();
        nomeEmptyLabel = new javax.swing.JLabel();
        utilizadorEncarregueLabel = new javax.swing.JLabel();
        utilizadorEncarregueValue = new javax.swing.JLabel();
        utilizadorEncarrregueEmptyLabel = new javax.swing.JLabel();
        prioridadeLabel1 = new javax.swing.JLabel();
        prioridadeSlider = new javax.swing.JSlider();
        prioridadeLabel2 = new javax.swing.JLabel();
        descriçãoScrollPane = new javax.swing.JScrollPane();
        descriçãoEditorPane = new javax.swing.JEditorPane();
        projetoValue = new javax.swing.JLabel();
        projetoLabel = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        listaTarefasEmptyLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(540, 680));
        setMinimumSize(new java.awt.Dimension(540, 680));
        setPreferredSize(new java.awt.Dimension(540, 680));
        setResizable(false);

        novoProjetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 28)); // NOI18N
        novoProjetoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novoProjetoLabel.setText("Nova Tarefa");

        descriçãoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        descriçãoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriçãoLabel.setText("Descrição");

        títuloLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        títuloLabel.setText("Título");

        títuloTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                títuloTextFieldKeyReleased(evt);
            }
        });

        selecionarButton.setText("Selecionar");
        selecionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selecionarButtonActionPerformed(evt);
            }
        });

        dataLimiteLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        dataLimiteLabel.setText("Data Limite");

        userAssociadosLista.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        userAssociadosLista.setToolTipText("");
        userAssociadosLista.setDragEnabled(true);
        userAssociadosLista.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                userAssociadosListaComponentShown(evt);
            }
        });
        userAssociadosScrollPane.setViewportView(userAssociadosLista);

        userAssociadosTabbedPane.addTab("Associados Projeto", userAssociadosScrollPane);

        criarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        criarButton.setText("Criar");
        criarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                criarButtonActionPerformed(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        horasLimiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        minutosLimiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minutosLimiteComboBox.setToolTipText("Horas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Minutos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Horas");

        dataLimiteChooserCombo.setFormat(1);
        dataLimiteChooserCombo.setFieldFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 18));
        dataLimiteChooserCombo.setLocale(new java.util.Locale("pt", "PT", ""));

        nomeEmptyLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        nomeEmptyLabel.setForeground(new java.awt.Color(250, 0, 0));
        nomeEmptyLabel.setText("*");

        utilizadorEncarregueLabel.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        utilizadorEncarregueLabel.setText("Utilizador encarregue:");

        utilizadorEncarregueValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        utilizadorEncarrregueEmptyLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        utilizadorEncarrregueEmptyLabel.setForeground(new java.awt.Color(250, 0, 0));
        utilizadorEncarrregueEmptyLabel.setText("*");

        prioridadeLabel1.setFont(new java.awt.Font("Lucida Console", 1, 14)); // NOI18N
        prioridadeLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prioridadeLabel1.setText("Baixa    Média    Alta");

        prioridadeSlider.setMajorTickSpacing(1);
        prioridadeSlider.setMaximum(2);
        prioridadeSlider.setMinorTickSpacing(1);
        prioridadeSlider.setValue(0);

        prioridadeLabel2.setFont(new java.awt.Font("Lucida Console", 1, 18)); // NOI18N
        prioridadeLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        prioridadeLabel2.setText("Prioridade");

        descriçãoScrollPane.setViewportView(descriçãoEditorPane);

        projetoValue.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                projetoValueMouseClicked(evt);
            }
        });

        projetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        projetoLabel.setText("Projeto");

        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel3.setText("Lista Tarefas");

        listaTarefasEmptyLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        listaTarefasEmptyLabel.setForeground(new java.awt.Color(250, 0, 0));
        listaTarefasEmptyLabel.setText("*");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(novoProjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 449, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(títuloLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addComponent(projetoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(dataLimiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 144, Short.MAX_VALUE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(títuloTextField)
                            .addComponent(projetoValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataLimiteChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(horasLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(minutosLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(descriçãoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(prioridadeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prioridadeSlider, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(prioridadeLabel1, javax.swing.GroupLayout.Alignment.LEADING))
                                    .addGap(29, 29, 29))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(listaTarefasEmptyLabel)
                                    .addGap(44, 44, 44)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(16, 16, 16)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                            .addComponent(utilizadorEncarregueValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 190, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(utilizadorEncarregueLabel, javax.swing.GroupLayout.Alignment.LEADING))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(utilizadorEncarrregueEmptyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(11, 11, 11)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selecionarButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userAssociadosTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(nomeEmptyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25))
            .addGroup(layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(voltarButton)
                .addGap(18, 18, 18)
                .addComponent(criarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(novoProjetoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(títuloLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(títuloTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeEmptyLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(projetoLabel)
                    .addComponent(projetoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataLimiteLabel)
                    .addComponent(dataLimiteChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(horasLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutosLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(utilizadorEncarregueLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(utilizadorEncarrregueEmptyLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(utilizadorEncarregueValue, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(listaTarefasEmptyLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridadeLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(prioridadeSlider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(userAssociadosTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(prioridadeLabel1)
                    .addComponent(selecionarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(criarButton))
                .addContainerGap(97, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void títuloTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_títuloTextFieldKeyReleased
        nomeEmptyLabel.setVisible(false);
        títuloTextField.setText(títuloTextField.getText());
        if (títuloTextField.getText().isEmpty()) {
            nomeEmptyLabel.setVisible(true);
        }
    }//GEN-LAST:event_títuloTextFieldKeyReleased

    private void userAssociadosListaComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_userAssociadosListaComponentShown

    }//GEN-LAST:event_userAssociadosListaComponentShown

    private void selecionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selecionarButtonActionPerformed
        if (!userAssociadosLista.isSelectionEmpty()) {//Se tiver selecionado um utilizador
            utilizadorEncarregueValue.setText(userAssociadosLista.getSelectedValue());//Seleciona-lo com encarregue
        }
        utilizadorEncarrregueEmptyLabel.setVisible(false);

    }//GEN-LAST:event_selecionarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        sistemaNovaTarefa.getDashboardWindow().refreshUI();//Atualiza as janels
        dispose();//Faz dispose da janela
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void projetoValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_projetoValueMouseClicked
        new ProjetoFrontEnd(sistemaNovaTarefa, projetoNovaTarefa).setVisible(true); //nova janela do projeto
    }//GEN-LAST:event_projetoValueMouseClicked

    private void criarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_criarButtonActionPerformed
        if (!sistemaNovaTarefa.getCurrentSave().getListaProjetosSave().getListaProjetos().contains(projetoNovaTarefa)) {//Se projeto não for encontrada
            JOptionPane.showMessageDialog(this, "Este projeto não existe ou foi eliminado", "Erro ao criar tarefa.", JOptionPane.ERROR_MESSAGE);//Mensagem de erro
            dispose(); //dispose da janela
        }
        String erro = "";
        String prioridade = "";

        if (dataLimiteChooserCombo.getSelectedDate() != null) {
            if (LocalDateTime.of(dataLimiteChooserCombo.getSelectedDate().get(Calendar.YEAR), dataLimiteChooserCombo.getSelectedDate().get(Calendar.MONTH) + 1, dataLimiteChooserCombo.getSelectedDate().get(Calendar.DAY_OF_MONTH), horasLimiteComboBox.getSelectedIndex(), minutosLimiteComboBox.getSelectedIndex()).isBefore(LocalDateTime.now())) { //se data limite for antes da data atual
                erro += "Data Limite inválida (Data antes de Hoje).\n";
            }
            if (LocalDateTime.of(dataLimiteChooserCombo.getSelectedDate().get(Calendar.YEAR), dataLimiteChooserCombo.getSelectedDate().get(Calendar.MONTH) + 1, dataLimiteChooserCombo.getSelectedDate().get(Calendar.DAY_OF_MONTH), horasLimiteComboBox.getSelectedIndex(), minutosLimiteComboBox.getSelectedIndex()).isAfter(projetoNovaTarefa.getDataLimiteProjeto())){
                erro += "Data Limite inválida (Data após data limite do Projeto).\n";
            }
            
        } else {
            erro += "Data Limite inválida.\n";
        }

        if (títuloTextField.getText().isEmpty()) {//se o título estiver vazio, adicionar ao erro
            erro += "Nome inválido.\n";
            títuloLabel.setVisible(true);
        }
        if (utilizadorEncarregueValue.getText().isEmpty()) {//Se utilizador encarregue não tiver, adicionar ao erro
            erro += "Utilizador encarregue não selecionado\n";
            utilizadorEncarrregueEmptyLabel.setVisible(true);
        }
        switch (prioridadeSlider.getValue()) {//prioridade selecionada
            case 0:
                prioridade = "Baixa";
                break;
            case 1:
                prioridade = "Média";
                break;
            case 2:
                prioridade = "Alta";
                break;
        }
        if (jComboBox1.getSelectedIndex() == -1) {//se não tiver nenuma selecionada, adicionar ao erro
            erro += "Lista de Tarefas não selecionada\n";
            listaTarefasEmptyLabel.setVisible(true);
        }

        if (!erro.isEmpty()) {//se houver errors
            JOptionPane.showMessageDialog(this, erro, "Erro ao criar nova Tarefa", JOptionPane.ERROR_MESSAGE);//Mensagem de erro
        } else {//se não houver erros
            Tarefa novaTarefa = new Tarefa(títuloTextField.getText(), descriçãoEditorPane.getText(), sistemaNovaTarefa.getCurrentUser(), sistemaNovaTarefa.getCurrentSave().getListaUsersSave().getUserListaUsers(utilizadorEncarregueValue.getText().substring(utilizadorEncarregueValue.getText().indexOf("( ") + 2, utilizadorEncarregueValue.getText().indexOf(" )"))), prioridade, LocalDateTime.of(dataLimiteChooserCombo.getSelectedDate().get(Calendar.YEAR), dataLimiteChooserCombo.getSelectedDate().get(Calendar.MONTH) + 1, dataLimiteChooserCombo.getSelectedDate().get(Calendar.DAY_OF_MONTH), horasLimiteComboBox.getSelectedIndex(), minutosLimiteComboBox.getSelectedIndex()));//cria nova tarefa
            ListaTarefas listaTarefas = (ListaTarefas) jComboBox1.getSelectedItem();
            if (!projetoNovaTarefa.getListasTarefas().contains(listaTarefas)) {//se a lista não for encontrada
                JOptionPane.showMessageDialog(this, "A lista de tarefas que selecionou não exite ou foi eleminada", "Erro ao criar tarefa.", JOptionPane.ERROR_MESSAGE);//mensagem de erro
                dispose(); //dispose da janela
            } else {
                listaTarefas.addTarefaListaTarefas(novaTarefa);//adicionar a tarefa à lista selecionada
                sistemaNovaTarefa.setSaved(false);//Atualiza o estado do sistema como não gravado
                sistemaNovaTarefa.getDashboardWindow().refreshUI();//atualiza o estado
                dispose();//faz dispose da janela
            }
        }

    }//GEN-LAST:event_criarButtonActionPerformed

    private void setLabelsVisible(boolean booleano) {//Método que torna os labels de erro visiveis ou não
        nomeEmptyLabel.setVisible(booleano);
        utilizadorEncarrregueEmptyLabel.setVisible(booleano);
        listaTarefasEmptyLabel.setVisible(booleano);
    }

    public void setUserListsModels() {//Método que adiciona utilizadores associados à lista modelo
        for (User user : projetoNovaTarefa.getListaAssociatedUsersProjeto().getListaUsers()) {
            usersAssociadosListModel.addElement(user.getNomeUser() + " ( " + user.getUsernameUser() + " )");
        }
        usersAssociadosListModel.addElement(projetoNovaTarefa.getOwnerProjeto().getNomeUser() + " ( " + projetoNovaTarefa.getOwnerProjeto().getUsernameUser() + " )");
        userAssociadosLista.setModel(usersAssociadosListModel);
    }

    public void setListaTarefasComboModel() {
        listaTarefasComboModel.addAll(projetoNovaTarefa.getListasTarefas());
        jComboBox1.setModel(listaTarefasComboModel);
    }

    public void setSelectedDate() {//Método que seleciona a data limite selecionada para 7 dias depois da data de hoje
        LocalDateTime instant = LocalDateTime.now();
        Calendar calendarStart = Calendar.getInstance();
        horasLimiteComboBox.setSelectedIndex(instant.getHour());
        minutosLimiteComboBox.setSelectedIndex(instant.getMinute());
        calendarStart.set(instant.getYear(), instant.getMonthValue() - 1, instant.getDayOfMonth());
        calendarStart.add(Calendar.DAY_OF_MONTH, 7);
        dataLimiteChooserCombo.setSelectedDate(calendarStart);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton criarButton;
    private datechooser.beans.DateChooserCombo dataLimiteChooserCombo;
    private javax.swing.JLabel dataLimiteLabel;
    private javax.swing.JEditorPane descriçãoEditorPane;
    private javax.swing.JLabel descriçãoLabel;
    private javax.swing.JScrollPane descriçãoScrollPane;
    private javax.swing.JComboBox<String> horasLimiteComboBox;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel listaTarefasEmptyLabel;
    private javax.swing.JComboBox<String> minutosLimiteComboBox;
    private javax.swing.JLabel nomeEmptyLabel;
    private javax.swing.JLabel novoProjetoLabel;
    private javax.swing.JLabel prioridadeLabel1;
    private javax.swing.JLabel prioridadeLabel2;
    private javax.swing.JSlider prioridadeSlider;
    private javax.swing.JLabel projetoLabel;
    private javax.swing.JLabel projetoValue;
    private javax.swing.JButton selecionarButton;
    private javax.swing.JLabel títuloLabel;
    private javax.swing.JTextField títuloTextField;
    private javax.swing.JList<String> userAssociadosLista;
    private javax.swing.JScrollPane userAssociadosScrollPane;
    private javax.swing.JTabbedPane userAssociadosTabbedPane;
    private javax.swing.JLabel utilizadorEncarregueLabel;
    private javax.swing.JLabel utilizadorEncarregueValue;
    private javax.swing.JLabel utilizadorEncarrregueEmptyLabel;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
