/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Projeto;
import BackEnd.Sistema;
import BackEnd.User;
import java.time.LocalDateTime;
import java.util.Calendar;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class NovoProjeto extends javax.swing.JFrame {

    private Sistema sistemaNovoProjeto;
    private Dashboard dashboard;
    DefaultListModel usersAssociadosListModel;
    DefaultListModel usersNãoAssociadosListModel;

    public NovoProjeto(Sistema sistema) {
        sistemaNovoProjeto = sistema;
        usersAssociadosListModel = new DefaultListModel();
        usersNãoAssociadosListModel = new DefaultListModel();
        initComponents();
        nomeEmptyLabel.setVisible(false); //torna o label
        setSelectedDate(); //carrega a data limite
        setUserListsModels();
        setDefaultCloseOperation(DISPOSE_ON_CLOSE); //Fechar janela faz dispose da janela
        setTitle(sistemaNovoProjeto.NOMEPROGRAMA + " - Novo Projeto"); //Título da janela
        setIconImage(sistemaNovoProjeto.getIconFrame()); //Ícon da janela
        setLocationRelativeTo(null); //Janela no meio do ecrã

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        novoProjetoLabel = new javax.swing.JLabel();
        descriçãoLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        nomeTextField = new javax.swing.JTextField();
        removerButton = new javax.swing.JButton();
        AdicionarButton = new javax.swing.JButton();
        dataLimiteLabel = new javax.swing.JLabel();
        userAssociadosTabbedPane = new javax.swing.JTabbedPane();
        userAssociadosScrollPane = new javax.swing.JScrollPane();
        userAssociadosLista = new javax.swing.JList<>();
        utilizadoresTabbedPane = new javax.swing.JTabbedPane();
        utilizadoresScrollPane = new javax.swing.JScrollPane();
        utilizadoresLista = new javax.swing.JList<>();
        jButton1 = new javax.swing.JButton();
        voltarButton = new javax.swing.JButton();
        horasLimiteComboBox = new javax.swing.JComboBox<>();
        minutosLimiteComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        dataLimiteChooserCombo = new datechooser.beans.DateChooserCombo();
        nomeEmptyLabel = new javax.swing.JLabel();
        descriçãoScrollPane = new javax.swing.JScrollPane();
        descriçãoEditorPane = new javax.swing.JEditorPane();
        dataLimiteLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(560, 700));
        setPreferredSize(new java.awt.Dimension(520, 700));
        setResizable(false);

        novoProjetoLabel.setFont(new java.awt.Font("Lucida Console", 0, 28)); // NOI18N
        novoProjetoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        novoProjetoLabel.setText("Novo Projeto");

        descriçãoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        descriçãoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        descriçãoLabel.setText("Descrição");

        nomeLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        nomeLabel.setText("Nome");

        nomeTextField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                nomeTextFieldKeyReleased(evt);
            }
        });

        removerButton.setText("Remover");
        removerButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerButtonActionPerformed(evt);
            }
        });

        AdicionarButton.setText("Adicionar");
        AdicionarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdicionarButtonActionPerformed(evt);
            }
        });

        dataLimiteLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        dataLimiteLabel.setText("Data Limite");

        userAssociadosLista.setToolTipText("");
        userAssociadosLista.setDragEnabled(true);
        userAssociadosScrollPane.setViewportView(userAssociadosLista);

        userAssociadosTabbedPane.addTab("Associados", userAssociadosScrollPane);

        utilizadoresScrollPane.setViewportView(utilizadoresLista);

        utilizadoresTabbedPane.addTab("Utilizadores", utilizadoresScrollPane);

        jButton1.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jButton1.setText("Criar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoProjetoButton(evt);
            }
        });

        voltarButton.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        horasLimiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23" }));

        minutosLimiteComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "00", "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31", "32", "33", "34", "35", "36", "37", "38", "39", "40", "41", "42", "43", "44", "45", "46", "47", "48", "49", "50", "51", "52", "53", "54", "55", "56", "57", "58", "59" }));
        minutosLimiteComboBox.setToolTipText("Horas");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel1.setText("Minutos");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        jLabel2.setText("Horas");

        dataLimiteChooserCombo.setFormat(1);
        dataLimiteChooserCombo.setFieldFont(new java.awt.Font("Dialog", java.awt.Font.BOLD, 18));

        nomeEmptyLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        nomeEmptyLabel.setForeground(new java.awt.Color(250, 0, 0));
        nomeEmptyLabel.setText("*");

        descriçãoScrollPane.setViewportView(descriçãoEditorPane);

        dataLimiteLabel1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        dataLimiteLabel1.setText("Hora Limite");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(novoProjetoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nomeTextField))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(dataLimiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(dataLimiteChooserCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 303, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(nomeEmptyLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(21, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(removerButton, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(userAssociadosTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(utilizadoresTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                                    .addComponent(AdicionarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 229, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(voltarButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(dataLimiteLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(horasLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(minutosLimiteComboBox, 0, 69, Short.MAX_VALUE))
                                .addComponent(descriçãoLabel, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(novoProjetoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(nomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(nomeEmptyLabel)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(dataLimiteChooserCombo, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                    .addComponent(dataLimiteLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(horasLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(dataLimiteLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minutosLimiteComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descriçãoScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(userAssociadosTabbedPane)
                    .addComponent(utilizadoresTabbedPane, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(removerButton)
                    .addComponent(AdicionarButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton)
                    .addComponent(jButton1))
                .addContainerGap(174, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nomeTextFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_nomeTextFieldKeyReleased
        nomeEmptyLabel.setVisible(false);
        if (nomeTextField.getText().isEmpty()) {
            nomeEmptyLabel.setVisible(true);
        }
    }//GEN-LAST:event_nomeTextFieldKeyReleased

    private void removerButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerButtonActionPerformed
        for (String usersSelecionados : userAssociadosLista.getSelectedValuesList()) {//Retira utilizador da listamodel de associados e adiciona-lo à lista de não associados
            usersNãoAssociadosListModel.addElement(usersSelecionados);
            usersAssociadosListModel.removeElement(usersSelecionados);
        }
    }//GEN-LAST:event_removerButtonActionPerformed

    private void AdicionarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdicionarButtonActionPerformed
        for (String usersSelecionados : utilizadoresLista.getSelectedValuesList()) {//Adiciona utilizador para a lista de assoacidos e remove-lo da lista de não associados
            usersAssociadosListModel.addElement(usersSelecionados);
            usersNãoAssociadosListModel.removeElement(usersSelecionados);
        }
    }//GEN-LAST:event_AdicionarButtonActionPerformed

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        sistemaNovoProjeto.getDashboardWindow().refreshUI(); //Atualiza as janelas
        dispose();//faz dispose da janela
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void novoProjetoButton(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoProjetoButton
        String erro = "";

        if (dataLimiteChooserCombo.getSelectedDate() != null) {
            if (LocalDateTime.of(dataLimiteChooserCombo.getSelectedDate().get(Calendar.YEAR), dataLimiteChooserCombo.getSelectedDate().get(Calendar.MONTH) + 1, dataLimiteChooserCombo.getSelectedDate().get(Calendar.DAY_OF_MONTH), horasLimiteComboBox.getSelectedIndex(), minutosLimiteComboBox.getSelectedIndex()).isBefore(LocalDateTime.now())) {
                erro += "Data Limite inválida (Data antes de hoje).\n";
            }
        } else {
            erro += "Data Limite inválida.\n";
        }

        if (nomeTextField.getText().isEmpty()) {
            erro += "Nome inválido.\n";
            nomeLabel.setVisible(true);
        }

        if (!erro.isEmpty()) {
            JOptionPane.showMessageDialog(this, erro, "Erro ao criar novo Projeto", JOptionPane.ERROR_MESSAGE);
        } else {
            Projeto novoProjeto = new Projeto(nomeTextField.getText(), descriçãoEditorPane.getText(), sistemaNovoProjeto.getCurrentUser(), LocalDateTime.of(dataLimiteChooserCombo.getSelectedDate().get(Calendar.YEAR), dataLimiteChooserCombo.getSelectedDate().get(Calendar.MONTH) + 1, dataLimiteChooserCombo.getSelectedDate().get(Calendar.DAY_OF_MONTH), horasLimiteComboBox.getSelectedIndex(), minutosLimiteComboBox.getSelectedIndex()));
            for (Object usernameAdicionado : usersAssociadosListModel.toArray()) {
                novoProjeto.getListaAssociatedUsersProjeto().addUserListaUsers(sistemaNovoProjeto.getCurrentSave().getListaUsersSave().getUserListaUsers(usernameAdicionado.toString().substring(usernameAdicionado.toString().indexOf("( ") + 2, usernameAdicionado.toString().indexOf(" )"))));   //FALTA LIMITAR A ENTRADA DE PARENTISES NOS NOMES    
            }
            sistemaNovoProjeto.getCurrentSave().getListaProjetosSave().getListaProjetos().add(novoProjeto);
            sistemaNovoProjeto.setSaved(false);
            sistemaNovoProjeto.getDashboardWindow().refreshUI();
            dispose();
        }
    }//GEN-LAST:event_novoProjetoButton

    public void setUserListsModels() {//Método que carrega a lista modelo com todos os utilizadores     
        for (User user : sistemaNovoProjeto.getCurrentSave().getListaUsersSave().getListaUsers()) {
            if (user != sistemaNovoProjeto.getCurrentUser()) {
                usersNãoAssociadosListModel.addElement(user.getNomeUser() + " ( " + user.getUsernameUser() + " )");
            }
        }
        userAssociadosLista.setModel(usersAssociadosListModel);
        utilizadoresLista.setModel(usersNãoAssociadosListModel);
    }

    public void setSelectedDate() {//Método que carrega a data limite do projeto para 1 mes depois da data atual
        LocalDateTime instant = LocalDateTime.now();
        Calendar calendarStart = Calendar.getInstance();
        horasLimiteComboBox.setSelectedIndex(instant.getHour());
        minutosLimiteComboBox.setSelectedIndex(instant.getMinute());
        calendarStart.set(instant.getYear(), instant.getMonthValue() - 1, instant.getDayOfMonth());
        calendarStart.add(Calendar.MONTH, 1);
        dataLimiteChooserCombo.setSelectedDate(calendarStart);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AdicionarButton;
    private datechooser.beans.DateChooserCombo dataLimiteChooserCombo;
    private javax.swing.JLabel dataLimiteLabel;
    private javax.swing.JLabel dataLimiteLabel1;
    private javax.swing.JEditorPane descriçãoEditorPane;
    private javax.swing.JLabel descriçãoLabel;
    private javax.swing.JScrollPane descriçãoScrollPane;
    private javax.swing.JComboBox<String> horasLimiteComboBox;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JComboBox<String> minutosLimiteComboBox;
    private javax.swing.JLabel nomeEmptyLabel;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JTextField nomeTextField;
    private javax.swing.JLabel novoProjetoLabel;
    private javax.swing.JButton removerButton;
    private javax.swing.JList<String> userAssociadosLista;
    private javax.swing.JScrollPane userAssociadosScrollPane;
    private javax.swing.JTabbedPane userAssociadosTabbedPane;
    private javax.swing.JList<String> utilizadoresLista;
    private javax.swing.JScrollPane utilizadoresScrollPane;
    private javax.swing.JTabbedPane utilizadoresTabbedPane;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
