/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.ListaTarefas;
import BackEnd.Projeto;
import BackEnd.Sistema;
import BackEnd.Tarefa;
import BackEnd.User;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class Perfil extends javax.swing.JFrame {

    private Sistema sistemaPerfil;
    private User userPerfil;

    public Perfil(Sistema sistema, User user) {
        sistemaPerfil = sistema;
        userPerfil = user;
        initComponents();
        setCurrentValues(); //Carrega os dados do perfil
        setTitle(Sistema.NOMEPROGRAMA + " - Perfil -  " + userPerfil.getNomeUser() + " ( " + userPerfil.getUsernameUser() + " )");//Título da janela
        setIconImage(sistemaPerfil.getIconFrame());// Ícon da janela
        setDefaultCloseOperation(DISPOSE_ON_CLOSE);//fechar a janela faz dispose da janela
        setLocationRelativeTo(null);//Janela no meio do ecrã
        if (userPerfil != sistemaPerfil.getCurrentUser()) {//Se o current use não for o user do perfil, torna o butão de editar perfil nã visível
            editarButton.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        voltarButton = new javax.swing.JButton();
        idadeLabel = new javax.swing.JLabel();
        dataRegistoLabel = new javax.swing.JLabel();
        perfilLabel = new javax.swing.JLabel();
        nomeLabel = new javax.swing.JLabel();
        sexoLabel = new javax.swing.JLabel();
        emailLabel = new javax.swing.JLabel();
        telemóvelLabel = new javax.swing.JLabel();
        usernameLabel = new javax.swing.JLabel();
        idadeValue = new javax.swing.JLabel();
        usernameValue = new javax.swing.JLabel();
        emailValue = new javax.swing.JLabel();
        telemóvelValue = new javax.swing.JLabel();
        dataRegistoValue = new javax.swing.JLabel();
        nomeValue = new javax.swing.JLabel();
        telemóvelLabel1 = new javax.swing.JLabel();
        numeroProjetosValue = new javax.swing.JLabel();
        sexoValue = new javax.swing.JLabel();
        numeroTarefasLabel = new javax.swing.JLabel();
        numeroTarefasValue = new javax.swing.JLabel();
        editarButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(456, 590));
        setResizable(false);

        voltarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        voltarButton.setText("Voltar");
        voltarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                voltarButtonActionPerformed(evt);
            }
        });

        idadeLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        idadeLabel.setText("Idade");
        idadeLabel.setToolTipText("Idade do utilizador");

        dataRegistoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        dataRegistoLabel.setText("D. Registo");
        dataRegistoLabel.setToolTipText("Data de Registo do utilizador");

        perfilLabel.setFont(new java.awt.Font("Lucida Console", 0, 36)); // NOI18N
        perfilLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        perfilLabel.setText("Perfil");

        nomeLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        nomeLabel.setText("Nome");
        nomeLabel.setToolTipText("Nome do utilizador");

        sexoLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        sexoLabel.setText("Sexo");
        sexoLabel.setToolTipText("Sexo do utilizador");

        emailLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        emailLabel.setText("Email");
        emailLabel.setToolTipText("Email do utilizador");

        telemóvelLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        telemóvelLabel.setText("Telemóvel");
        telemóvelLabel.setToolTipText("Número de telemóvel do utilizador");

        usernameLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        usernameLabel.setText("Username");
        usernameLabel.setToolTipText("Username do utilizador");

        idadeValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        usernameValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        usernameValue.setToolTipText(userPerfil.getUsernameUser());

        emailValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        emailValue.setToolTipText(userPerfil.getEmailUser());

        telemóvelValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        telemóvelValue.setToolTipText(userPerfil.getTelemóvelUser());

        dataRegistoValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        nomeValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        nomeValue.setToolTipText(userPerfil.getNomeUser());

        telemóvelLabel1.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        telemóvelLabel1.setText("Nº de Projetos");
        telemóvelLabel1.setToolTipText("Número de Projetos inacabados criado pelo utilizador");

        numeroProjetosValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        sexoValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        numeroTarefasLabel.setFont(new java.awt.Font("Lucida Console", 0, 18)); // NOI18N
        numeroTarefasLabel.setText("Nº de Tarefas");
        numeroTarefasLabel.setToolTipText("Número de Tarefas inacabados associadas ao utilizador");

        numeroTarefasValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N

        editarButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        editarButton.setText("Editar");
        editarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(numeroTarefasLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dataRegistoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sexoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(nomeLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(usernameLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(idadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(emailLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telemóvelLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(telemóvelLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(numeroTarefasValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(numeroProjetosValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 188, Short.MAX_VALUE)
                                .addComponent(dataRegistoValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(telemóvelValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(usernameValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(sexoValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(idadeValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(emailValue, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addComponent(perfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(124, 124, 124)
                .addComponent(voltarButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 153, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {editarButton, voltarButton});

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(perfilLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(usernameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 34, Short.MAX_VALUE)
                    .addComponent(usernameValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nomeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nomeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(sexoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(idadeValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(idadeLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(emailValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(emailLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(telemóvelLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telemóvelValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dataRegistoValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataRegistoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroProjetosValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(telemóvelLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(numeroTarefasValue, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(numeroTarefasLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(voltarButton, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(editarButton))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {editarButton, voltarButton});

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void voltarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_voltarButtonActionPerformed
        dispose();//faz dispose da janela
    }//GEN-LAST:event_voltarButtonActionPerformed

    private void editarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarButtonActionPerformed
        new EditarPerfil(sistemaPerfil).setVisible(true);//nova janela EditarPerfil
        dispose();//faz dispose da janela
    }//GEN-LAST:event_editarButtonActionPerformed
    public void setCurrentValues() { //Método que carrega os dados do perfil
        usernameValue.setText(userPerfil.getUsernameUser());//Carrega o username do user
        nomeValue.setText(userPerfil.getNomeUser());
        if (userPerfil.getSexoUser() == 'm') { //Carrega o sexo do user
            sexoValue.setText("Masculino");
        }
        if (userPerfil.getSexoUser() == 'f') {
            sexoValue.setText("Feminino");
        }
        if (!(userPerfil.getDataNascimentoUser() == null)) { //Carrega a data de nascimento do user
            idadeValue.setText(String.valueOf(userPerfil.getIdadeUser()));
        }
        if (!(userPerfil.getEmailUser() == null)) {  //Carrega o email do user
            emailValue.setText(userPerfil.getEmailUser());
        }
        if (!(userPerfil.getTelemóvelUser() == null)) { //Carrega o número de telemóvel do user
            telemóvelValue.setText(userPerfil.getTelemóvelUser());
        }
        dataRegistoValue.setText(userPerfil.getDataInscriçãoUser().toString());     //Carrega a data de registo do user
        int numeroProjetos = 0;
        int numeroTarefas = 0;
        for (Projeto projeto : sistemaPerfil.getCurrentSave().getListaProjetosSave().getListaProjetos()) {//Ciclo para determinar a quantidade projetos e tarefas associadas ao user
            if (userPerfil.equals(projeto.getOwnerProjeto())) {
                numeroProjetos++;
            }
            for (ListaTarefas listatarefas : projeto.getListasTarefas()) {
                for (Tarefa tarefa : listatarefas.getListaTarefas()) {
                    if (!tarefa.isConcluídaTarefa() && tarefa.getOwnerTarefa().equals(userPerfil)) {
                        numeroTarefas++;
                    }
                }
            }
        }
        numeroProjetosValue.setText(String.valueOf(" " + numeroProjetos));//carrega o número de projetos a qual o user é owner
        numeroTarefasValue.setText(String.valueOf(" " + numeroTarefas));//carrega o número de tarefas a qual o user é associado
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel dataRegistoLabel;
    private javax.swing.JLabel dataRegistoValue;
    private javax.swing.JToggleButton editarButton;
    private javax.swing.JLabel emailLabel;
    private javax.swing.JLabel emailValue;
    private javax.swing.JLabel idadeLabel;
    private javax.swing.JLabel idadeValue;
    private javax.swing.JLabel nomeLabel;
    private javax.swing.JLabel nomeValue;
    private javax.swing.JLabel numeroProjetosValue;
    private javax.swing.JLabel numeroTarefasLabel;
    private javax.swing.JLabel numeroTarefasValue;
    private javax.swing.JLabel perfilLabel;
    private javax.swing.JLabel sexoLabel;
    private javax.swing.JLabel sexoValue;
    private javax.swing.JLabel telemóvelLabel;
    private javax.swing.JLabel telemóvelLabel1;
    private javax.swing.JLabel telemóvelValue;
    private javax.swing.JLabel usernameLabel;
    private javax.swing.JLabel usernameValue;
    private javax.swing.JButton voltarButton;
    // End of variables declaration//GEN-END:variables
}
