/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Projeto;
import BackEnd.Sistema;
import java.awt.Color;

/**
 * @author Flávio Santos(a89960)
 * @author João Silva(a89956)
 * @author Pedro Magalhães(a89169)
 */
public class ProjetoDisplay extends javax.swing.JPanel {

    private Sistema sistema;
    private Projeto projeto;

    public ProjetoDisplay(Sistema sistema, Projeto projeto) {
        this.projeto = projeto;
        this.sistema = sistema;
        initComponents();
        setValues();
    }

    public ProjetoDisplay(Sistema sistema, Projeto projeto, String string) {//construtor com um parâmetro string é adicionada ao valor do título do projeto
        this.projeto = projeto;
        this.sistema = sistema;
        initComponents();
        setValues();//carrega os dados do projeto
        títuloValue.setText(títuloValue.getText() + string);//parâmetro string é adicionada ao valor do título do projeto
    }

    public void setValues() {
        títuloValue.setText("Título : " + projeto.getTítuloProjeto());//carrega o título do projeto
        ownerValue.setText("Owner : " + projeto.getOwnerProjeto().getNomeUser() + " ( " + projeto.getOwnerProjeto().getUsernameUser() + " )");//Carrea o nome e username do utilizador
        if (projeto.getIsConcluídoProjeto()) {
            tempoRestanteValue.setText("Terminado a : " + projeto.getDataConclusãoProjeto().toLocalDate().toString() + " " + projeto.getDataConclusãoProjeto().getHour() + " : " + projeto.getDataConclusãoProjeto().getMinute());
            if (projeto.getDataConclusãoProjeto().isAfter(projeto.getDataLimiteProjeto())) {
                tempoRestanteValue.setForeground(Color.red);
            } else {
                tempoRestanteValue.setForeground(new Color(34, 139, 34));
            }
        } else {
            if (!projeto.isAtrasadoProjeto()) {//se o projeto estiver atrasado torna a cor do text vermelha
                tempoRestanteValue.setForeground(new Color(34, 139, 34)); //
                tempoRestanteValue.setText(projeto.getTempoStringProjeto());
            } else {//se o projeto não estiver atrasado torna a cor do text verde
                tempoRestanteValue.setForeground(Color.red);
                tempoRestanteValue.setText(projeto.getTempoStringProjeto());
            }
        }

        utilizadoresValue.setText("N. Envolvidos : " + projeto.getNumeroUsers());

        String tarefasString = " tarefas concluídas de ";//tratmento do plura e singular da string
        if (projeto.getNumeroTarefas() == 1) {
            tarefasString = " tarefa concluída de ";
        }
        progressoLabel.setText(projeto.getNumeroTarefasConcluidas() + tarefasString + projeto.getNumeroTarefas());
        if (projeto.getNumeroTarefas() > 0) {
            jProgressBar1.setValue(projeto.getNumeroTarefasConcluidas());
            jProgressBar1.setMaximum(projeto.getNumeroTarefas());
            if (jProgressBar1.getPercentComplete() <= 0.25) {//se a percentagem  de trarefas concluídas for meno que 25% torna a cor da barra de progresso vermelha
                jProgressBar1.setBackground(Color.RED);
            } else if (jProgressBar1.getPercentComplete() >= 0.75) {//se a percentagem  de tarefas concluídas for maior que 75% torna a cor da barra de progresso verde
                jProgressBar1.setBackground(new Color(34, 139, 34));
            } else { //se a percentagem  de tarefas concluídas for entre 25% e 75% torna a cor da barra de progresso amarela
                jProgressBar1.setBackground(Color.yellow);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        títuloValue = new javax.swing.JLabel();
        ownerValue = new javax.swing.JLabel();
        tempoRestanteValue = new javax.swing.JLabel();
        progressoLabel = new javax.swing.JLabel();
        jProgressBar1 = new javax.swing.JProgressBar();
        utilizadoresValue = new javax.swing.JLabel();

        setBackground(new java.awt.Color(204, 204, 204));
        setForeground(new java.awt.Color(60, 63, 65));
        setToolTipText("");
        setMaximumSize(new java.awt.Dimension(625, 100));
        setMinimumSize(new java.awt.Dimension(625, 100));
        setName(""); // NOI18N
        setPreferredSize(new java.awt.Dimension(625, 100));

        títuloValue.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        títuloValue.setForeground(new java.awt.Color(60, 63, 65));
        títuloValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                títuloValueMouseClicked(evt);
            }
        });

        ownerValue.setForeground(new java.awt.Color(60, 63, 65));
        ownerValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);
        ownerValue.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ownerValueMouseClicked(evt);
            }
        });

        tempoRestanteValue.setForeground(new java.awt.Color(60, 63, 65));
        tempoRestanteValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        progressoLabel.setForeground(new java.awt.Color(60, 63, 65));
        progressoLabel.setText("Progresso");

        jProgressBar1.setStringPainted(true);

        utilizadoresValue.setForeground(new java.awt.Color(60, 63, 65));
        utilizadoresValue.setHorizontalAlignment(javax.swing.SwingConstants.TRAILING);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(progressoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jProgressBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(títuloValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(ownerValue, javax.swing.GroupLayout.DEFAULT_SIZE, 275, Short.MAX_VALUE)
                    .addComponent(utilizadoresValue, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tempoRestanteValue, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(27, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(ownerValue, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(utilizadoresValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(tempoRestanteValue, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(títuloValue, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(progressoLabel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jProgressBar1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ownerValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ownerValueMouseClicked
        new Perfil(sistema, projeto.getOwnerProjeto()).setVisible(true); //nova janela de perfil do owner do projeto
    }//GEN-LAST:event_ownerValueMouseClicked

    private void títuloValueMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_títuloValueMouseClicked
        new ProjetoFrontEnd(sistema, projeto).setVisible(true); //nova janela do Projeto
    }//GEN-LAST:event_títuloValueMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel ownerValue;
    private javax.swing.JLabel progressoLabel;
    private javax.swing.JLabel tempoRestanteValue;
    private javax.swing.JLabel títuloValue;
    private javax.swing.JLabel utilizadoresValue;
    // End of variables declaration//GEN-END:variables
}
